### ISSUE TITLE
Don't track binaries or imported TF-M files in git

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-os-tf-m-regression-tests#12]
We shouldn't track binaries or TF-M files in git. Any autogenerated, compiled, or copied code shouldn't be in version control. We should instead generate the files on-demand when running this application.

Having TF-M files tracked in our repo may confuse folks wishing to make changes to those files. Having them always import makes it clear the files would need changing upstream.

Binaries don't need to be tracked because they can be generated as needed from the source code.

**Comment by LDong-Arm** [comment]
Fixed by #67
