### ISSUE TITLE
Move target specific configurations PSA_API_TARGETS

### ISSUE THREAD

**Issue by urutva** [ARMmbed/mbed-os-tf-m-regression-tests#2]
The target specific configuration `PSA_API_TARGETS` in `build_psa_compliance.py` should be moved to `mbed-os/targets/targets.json` to avoid duplication of target configs in `targets.json` and build scripts.

**Comment by LDong-Arm** [comment]
From TF-M v1.2 onwards, the TF-M build system handles the build of PSA compliance tests. The new command option is simply `-DTEST_PSA_API=[musca_s1|musca_b1]` without manual mappings.

Closing this issue.
