### ISSUE TITLE
Fix: Long path issue on Windows when using `build_tfm.py`

### ISSUE THREAD

**Issue by jainvikas8** [ARMmbed/mbed-os-tf-m-regression-tests#25]
The build fails when using the script. For example, if standalone script is executed:

```$python3 build_tfm.py -m ARM_MUSCA_B1 -t GNUARM -c ConfigRegressionIPC.cmake```

```
[Build-TF-M] 15:57:22: [  8%] [32mBuilding C object secure_fw/CMakeFiles/tfm_s_obj_lib.dir/__/platform/ext/target/musca.b1/Native_Driver/musca_b1_eflash_drv.o[0m
.Build-TF-M] 15:57:23: Assembler messages:
[Build-TF-M] 15:57:23: Fatal error: can't create CMakeFiles/tfm_s_obj_lib.dir/__/platform/ext/target/musca_b1/Native_Dri.er/musca_b1_eflash_drv.o: No such file or directory
[Build-TF-M] 15:57:23: make.exe[2]: *** [secure_fw/CMakeFiles/tfm_s_obj_lib.dir/build.make:591: secure_fw/CMakeFiles/tfm.s_obj_lib.dir/__/platform/ext/target/musca_b1/Native_Driver/musca_b1_eflash_drv.o] Error 1
.Build-TF-M] 15:57:23: make.exe[1]: *** [CMakeFiles/Makefile2:109: secure_fw/CMakeFiles/tfm_s_obj_lib.dir/all] Error 2
.Build-TF-M] 15:57:23: make.exe: *** [Makefile:130: all] Error 2
```

On closer investigation, it seems to be Windows O.S limitation with path being too long

```
[Build-TF-M] 17:43:01: CMake Warning in secure_fw/services/internal_trusted_storage/CMakeLists.txt:.
[Build-TF-M] 17:43:01:   The object file directory.
[Build-TF-M] 17:43:01: .
[Build-TF-M] 17:43:01:     C:/Work/Workspace/mbed-os-tf-m-regression-tests/mbed-os/features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_IGNORE/trusted-firmware-m/cmake_build/secure_fw/services/internal_trusted_storage/CMakeFiles/tfm_internal_trusted_storage.dir/.
[Build-TF-M] 17:43:01: .
[Build-TF-M] 17:43:01:   has 246 characters.  The maximum full path to an object file is 250.
[Build-TF-M] 17:43:01:   characters (see CMAKE_OBJECT_PATH_MAX).  Object file.
[Build-TF-M] 17:43:01: .
[Build-TF-M] 17:43:01:     flash_fs/its_flash_fs.o.
[Build-TF-M] 17:43:01: .
[Build-TF-M] 17:43:01:   cannot be safely placed under this directory.  The build may not work.
[Build-TF-M] 17:43:01:   correctly..
```

**Comment by LDong-Arm** [comment]
Similar issue happens again: #117

This time there's not much we can do in mbed-os-tf-m-regression-tests, because the paths used by trusted-firmware-m seem to have become quite a bit longer than before...

**Comment by jeromecoutant** [comment]
It is strange that this issue has been closed with no solution... or no big warning in the readme file:

WARNING: if you are working with Windows machine, you can't build TFM regression tests....

@MarceloSalazar

**Comment by LDong-Arm** [comment]
> It is strange that this issue has been closed with no solution... or no big warning in the readme file:
> 
> WARNING: if you are working with Windows machine, you can't build TFM regression tests....
> 
> @MarceloSalazar

It was not closed without solution. In fact, TF-M v1.2 version didn't have as long paths as the current, and #96 was enough to fix the issue on Windows most of the time. It was only from TF-M v1.3 when the paths grew much much longer.
