### ISSUE TITLE
Builder fails to report on git clone errors

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-os-tf-m-regression-tests#38]
Function `check_and_clone_repo()` fails to actually fail when git fails to clone a repo. This could be fixed by verifying that the directory is created or by seeing if git returns an error status (via command line).

**Comment by LDong-Arm** [comment]
Fix created: #62 
By adding checks to `check_and_clone_repo()`, we uncover a bug in the checkout of tag/SHA1 which is also fixed by that PR.
