### ISSUE TITLE
Refactor `srec_cat` with `pyocd` in test_psa_target.py

### ISSUE THREAD

**Issue by jainvikas8** [ARMmbed/mbed-os-tf-m-regression-tests#46]
`pyocd erase -c -t musca_b1` would seem to be a better approach as its more generic and erase the chip instead of configuring which sections to erase for the targets, but there seems to be a bug - mbedmicro/pyOCD#916 for `ARM_MUSCA_B1`. 

So refactor this code for all targets to use `pyocd`.

**Comment by LDong-Arm** [comment]
As far as I understand and experimented, `pyocd erase` does not work on Musca S1. Since `srec_cat` is recommended by TF-M's documentation, it's okay to use it at this point.

**Comment by jainvikas8** [comment]
> As far as I understand and experimented, `pyocd erase` does not currently work on Musca S1. Since `srec_cat` is recommended by TF-M's documentation, it's okay to use it at this point.

Considering the comment above, closing the ticket.
