### ISSUE TITLE
Toolchain argument not passed down in build_psa_compliance.py

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/mbed-os-tf-m-regression-tests#54]
### Environment

**mbed-os-tf-m-regression-tests**
3d165544672acf537b8c66db6cee313d8d6fe391

**mbed-os**
2f87d59c7f2eed226ff82df72d2724b0ac122177

**ARMCLANG**
ARM Compiler 6.12

### Steps to reproduce

Edit `mbed_app.json` to disable `regression-test` and enable `psa-compliance-test` as documented:

```json
{
    "config": {
        "regression-test": 0,
        "psa-compliance-test": 1
    },
    ......
}
```

Build PSA compliance test:

```sh
python3 build_psa_compliance.py -m ARM_MUSCA_B1 -s CRYPTO -t ARMCLANG
```

Seeing into, the `ARMCLANG` toolchain argument isn't passed down. Try patching it manually by:

**build_psa_compliance.py**:
```python
def _run_cmake_build(cmake_build_dir, args):
    ......
    if args.range:
        cmake_cmd.append("-DSUITE_TEST_RANGE=" + args.range)

    # Add missing toolchain
    if args.toolchain:
        cmake_cmd.append("-DTOOLCHAIN=" + args.toolchain)

    retcode = run_cmd_output_realtime(cmake_cmd, cmake_build_dir)
    ......
```

**Comment by LDong-Arm** [comment]
@ccli8 Merged to the master branch, thanks for the suggestion
