### ISSUE TITLE
Support multi-level TF-M target name

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/mbed-os-tf-m-regression-tests#85]
I am enabling TF-M/Mbed integration on Nuvoton's M2354 target. Currently, M2354 port has landed into [TF-M repo](https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/7736).  To enable Mbed/TF-M 1.2 integration on M2354, I base on this repo's `tf-m-v1.2-integration` branch. Slight different, compared to 1-level TF-M target name `musca_b1` or `musca_s1`, M2354's TF-M target name is 2-level `nuvoton/m2354`. Currently, I find `s_veneers.o` source copy path is incorrect for multi-level TF-M target name

https://github.com/ARMmbed/mbed-os-tf-m-regression-tests/blob/328ea8efc6a24c00c60dcfc033eee168737e3159/build_tfm.py#L351

It should correct to below for 2-level TF-M target name:
```python
        install_dir = abspath(join(source, os.pardir, os.pardir, os.pardir))
```

**Comment by jainvikas8** [comment]
Thanks for raising this issue, please can you raise a PR against - https://github.com/ARMmbed/mbed-os-tf-m-regression-tests/tree/tf-m-v1.2-integration

**Comment by jainvikas8** [comment]
Closing the issue as the PR got merged.
